Add Romanian language
hustcc/timeago.js pull request #75
Opened 2016-09-22 15:55 UTC by liviuroman

2016-09-22 17:20 UTC, likerRr requested changes
Thank you! Please, add tests like it's done for [other languages](https://github.com/hustcc/timeago.js/tree/master/tests/locales)

2016-09-23 01:21 UTC, hustcc commented
```js
var timeType = parseInt((index + 1) / 2);
```

This can do, no need to switch ... case.

2016-09-23 06:05 UTC, likerRr commented
@hustcc not sure that we can replace switch/case with such code. Compare results for case 2 and 3:

```javascript
parseInt((2 + 1) / 2); // 1
parseInt((3 + 1) / 2); // 2
// but result should be 2 in both cases
```

Hope, that `Math.ceil((index + 1) / 2)` can help:

```javascript
Math.ceil((1 + 1) / 2); // 1

Math.ceil((2 + 1) / 2); // 2
Math.ceil((3 + 1) / 2); // 2

Math.ceil((4 + 1) / 2); // 3
Math.ceil((5 + 1) / 2); // 3

Math.ceil((6 + 1) / 2); // 4
Math.ceil((7 + 1) / 2); // 4

Math.ceil((8 + 1) / 2); // 5
Math.ceil((9 + 1) / 2); // 5

Math.ceil((10 + 1) / 2); // 6
Math.ceil((11 + 1) / 2); // 6

Math.ceil((12 + 1) / 2); // 7
Math.ceil((13 + 1) / 2); // 7
```

2016-09-23 06:06 UTC, likerRr commented on locales/ro.js
> +        case 13: timeType = 7; break;
[Simplify switch/case](https://github.com/hustcc/timeago.js/pull/75#issuecomment-249110364)

2016-09-23 06:08 UTC, likerRr commented on locales/ro.js
> +    if (number == 1)
Wrap `if`s in curly braces until it's one-line `if`

2016-09-23 06:09 UTC, likerRr requested changes
Please, fix remaining parts

2016-09-23 06:11 UTC, hustcc commented on locales/ro.js
> +        case 13: timeType = 7; break;
:+1:

2016-09-24 18:04 UTC, likerRr commented on locales/ro.js
> +        case 13: timeType = 7; break;
@hustcc open tab "Files changed" and find green button "Review Changes". Read more [here](https://github.com/blog/2256-a-whole-new-github-universe-announcing-new-tools-forums-and-features) or view a [video](https://www.youtube.com/watch?v=HW0RPaJqm4g).

2016-09-25 13:12 UTC, likerRr commented
@liviuroman thank you for updates. Resolve conflicts and we will approve the PR.

2016-09-26 06:32 UTC, likerRr commented
@liviuroman sorry, but conflicts still haven't resolved. I think it would be better to close this PR and open a new one, because there are already 9 commits for just adding new locale. It's too much. 

Please, get latest changes from timeago's `master`, apply [patch](https://patch-diff.githubusercontent.com/raw/hustcc/timeago.js/pull/75.patch) from this PR, resolve conflicts (please, done this all locally) and then open a new PR with single commit.

2016-09-26 06:32 UTC, closed without merging